with col2:
    st.subheader("3. Generated Quiz Output")
    
    if st.session_state.is_generating:
        st.components.v1.html("""
            <script>
            window.addEventListener('beforeunload', function (e) {
                e.preventDefault();
                e.returnValue = '';
            });
            </script>
        """, height=0)

        status_box = st.empty()
        progress_bar = st.progress(0)
        output_container = st.empty()
        
        status_box.info("⚡ Preparing lecture slides for AI context...")
        progress_bar.progress(15)
        
        combined_styles = ""
        session_instructions = ""
        inline_slide_context = ""
        total_slides_char_count = 0
        
        k = len(selected_session_titles)
        base_quota = num_questions // k
        remainder = num_questions % k
        
        try:
            for idx, title in enumerate(selected_session_titles):
                quota = base_quota + (1 if idx < remainder else 0)
                sess = sessions_dict[title]
                slides_text = sess.get("slides", "")

                status_box.info(f"⚡ Processing slides for session '{title}' ({idx + 1}/{k})...")

                cleaned_slides = "\n".join([line.strip() for line in slides_text.splitlines() if line.strip()])
                total_slides_char_count += len(cleaned_slides)
                
                inline_slide_context += f"\n\nLECTURE SLIDES FOR SESSION: '{title}'\n{cleaned_slides}\n"
                session_instructions += f"\n- Session '{title}': Generate exactly {quota} question(s)."
                
                sess_style = sess.get("style_profile")
                if sess_style:
                    combined_styles += f"\n--- Faculty Writing Style Guidelines for {title} ---\n" + sess_style
                elif global_course_style:
                    combined_styles += f"\n--- Course-Wide Faculty Writing Style Guidelines ---\n" + global_course_style

            # Check if extracted slides actually contain text
            if total_slides_char_count < 50:
                raise ValueError("The selected session slides appear to be empty or missing text in the database. Please re-upload the slides in Faculty Studio.")

            progress_bar.progress(40)
            status_box.info("🧠 Analyzing slide contents & matching faculty writing style...")

            prompt_text = f"""
            You are a medical school faculty member writing completely original, high-yield in-house exam practice questions for medical students enrolled in {selected_course}.
            
            --- LECTURE SLIDES REFERENCE DATA ---
            {inline_slide_context}

            --- CRITICAL GROUNDING RULES ---
            1. STRICT SCOPE: All questions, options, and distractors MUST be grounded STRICTLY in facts explicitly stated in the provided lecture slide documents above.
            2. FACULTY STYLE: Match the faculty's exact tone, clinical vignette complexity, stem phrasing, and distractor design.
            3. OBJECTIVES ALIGNMENT: Ensure questions test session learning objectives.
            4. FORMAT: Do NOT use LaTeX delimiters or math formatting (e.g., do NOT use $, $$, \\frac). Write all units and formulas in standard plain text.
            5. RANDOMIZED CORRECT ANSWERS: Vary correct answer placement unpredictably across A, B, C, D, and E.
            6. SLIDE CITATIONS: In Section 2, every question rationale MUST cite the exact slide number from the slides above.

            --- TARGET QUESTION DISTRIBUTION PER SESSION ---
            {session_instructions}

            --- IN-HOUSE FACULTY QUESTION WRITING STYLE GUIDELINES ---
            {combined_styles if combined_styles else "Write clear, high-yield in-house medical school exam questions based strictly on the slides."}

            --- ARRANGEMENT & FORMATTING ---
            * Total Questions to generate: {num_questions}.
            * Arrangement Mode: '{arrange_mode}'.
            
            SECTION 1: QUESTIONS
            Question [Number]
            [Vignette / Stem]
            A) ...
            B) ...
            C) ...
            D) ...
            E) ...

            SECTION 2: ANSWER KEY & RATIONALES
            Question [Number]
            - Session: [Session Title]
            - Correct Answer: [Letter A-E]
            - Detailed Rationale: Explaining why option is right based on slide facts.
            - Exact Slide Citation: Slide [Number] ([Slide Topic/Heading])

            Generated by Jacobs Practice Question Generator, in accordance with the JSMBS Generative Artificial Intelligence Use Policy for Medical Students in the Medical Curriculum.
            """

            full_text = ""
            STABLE_MODELS = ["gemini-2.5-flash", "gemini-1.5-flash"]
            last_error = ""

            for target_model in STABLE_MODELS:
                try:
                    status_box.info(f"✍️ Generating questions using engine `{target_model}`...")
                    progress_bar.progress(60)
                    
                    response = client.models.generate_content(
                        model=target_model,
                        contents=prompt_text
                    )
                    
                    if response and response.text and response.text.strip():
                        full_text = response.text.strip()
                        output_container.code(full_text, language="markdown")
                        break
                except Exception as model_err:
                    last_error = str(model_err)
                    print(f"Model {target_model} failed: {model_err}")
                    time.sleep(1)
                    continue

            if not full_text:
                raise Exception(f"API generation failed. Last model error: {last_error if last_error else 'Unknown error'}")

            st.session_state.generated_quiz = full_text
            st.session_state.is_generating = False
            st.rerun()

        except Exception as e:
            print(f"[{datetime.now().isoformat()}] Quiz generation failed: {e}")
            traceback.print_exc()

            st.session_state.is_generating = False
            status_box.empty()
            progress_bar.empty()
            st.error(f"Error generating questions: {e}")

    elif st.session_state.generated_quiz:
        st.success("🎉 Practice Quiz Active")
        
        tb_col1, tb_col2, tb_col3 = st.columns([6, 1.5, 1.5])
        
        with tb_col2:
            st.download_button(
                label="📄 .TXT",
                data=st.session_state.generated_quiz,
                file_name=f"{selected_course.replace(' ', '_')}_Practice_Quiz.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        with tb_col3:
            docx_data = create_docx(st.session_state.generated_quiz)
            st.download_button(
                label="📝 .DOCX",
                data=docx_data,
                file_name=f"{selected_course.replace(' ', '_')}_Practice_Quiz.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
            
        st.code(st.session_state.generated_quiz, language="markdown")

    else:
        st.info("Select options on the left and click 'Generate Practice Quiz' to create questions.")
